# Generated by Django 5.0.6 on 2024-06-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('direccion', models.TextField(max_length=150, verbose_name='Nombre Cliente')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Cliente')),
                ('password', models.CharField(max_length=10, verbose_name='Contraseña')),
            ],
        ),
    ]
