# Generated by Django 5.0.6 on 2024-06-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('descripcion', models.EmailField(max_length=277, verbose_name='Detalle del Producto')),
                ('precio', models.CharField(max_length=20, verbose_name='Precio')),
                ('cantidad', models.CharField(max_length=20, verbose_name='Cantidad')),
            ],
        ),
    ]
